name: run-test-suite
run-name: run test suite
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SBCL
        run: >
          sudo apt-get update &&
          sudo apt-get install sbcl
        
      - name: Greet
        run: sbcl --non-interactive --eval '(format t "blub~%")'
