name: run-test-suite
run-name: run test suite
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin

    env:
      LISP: ${{ matrix.lisp }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Lisp
        uses: 40ants/setup-lisp@v3
        with:
          asdf-system: cl-info

      - uses: 40ants/run-tests@v3
        with:
          asdf-system: cl-info

